### ISSUE TITLE
Any way you could port this to ROS Noetic?

### ISSUE THREAD

**Issue by LFS-Robotics** [srmainwaring/wave_sim_vrx#1]
Any chance of a Noetic port of this ?

**Comment by srmainwaring** [comment]
@LFS-Engineering, I believe most of the functionality from this repo has now been incorporated into the vrx project directly.

This repo, wave_sim_vrx, is a hard fork of [asv_wave_sim](https://github.com/srmainwaring/asv_wave_sim) with all the GPL dependencies removed (and most of the functionality). The vrx team wanted to incorporate the approach used here to synchronise the visuals with the server physics and this repo was prepared to help with that. It's maintenance only I'm afraid and I'm not planning to port to Noetic as my focus is ROS2 Humble and Gazebo Garden. I'd be happy to accept a PR however if you are interesting in submitting a port yourself.

**Comment by LFS-Robotics** [comment]
Thanks for the quick response, understandable. Was just having issues with the asv_wave_sim configuration. But will keep trying to get that working.

**Comment by srmainwaring** [comment]
If you want some help with asv_wave_sim feel free to log an issue with a help tag. As I mentioned above the focus is mostly on ROS2 / Gazebo Garden and later as I support Ubuntu and macOS, and macOS support for ROS1 just got too difficult after macOS Catalina. There are a couple of branches of asv_wave_sim that do target Gazebo classic (9 and 11). The master branch no longer has any ROS dependency, except perhaps the build tool which is now colcon.

**Comment by alexdrc00** [comment]
Just a quick question, @srmainwaring, has asv_wave_sim then been incorporated into vrx 2.0 or later releases? I have been testing changing wave parameters but I could not see any relevant visual changes on the waves nor a real displacement of the wamv. I just want to make sure what the issue is in case it has anything to do with a mistake in the installation on my side. Thanks

**Comment by srmainwaring** [comment]
> Just a quick question, @srmainwaring, has asv_wave_sim then been incorporated into vrx 2.0 or later releases?

No, only the features mentioned above at the point this fork was created.

The main branch of [asv_wave_sim](https://github.com/srmainwaring/asv_wave_sim) has evolved significantly and there are currently no plans to incorporated it into VRX.

I will archive this repo to make it clear that it is available, but not being developed.
